services:
  scanner:
    image: derhenning/tgtg:latest-alpine ## pre build image from docker hub
    # image: tgtg-scanner:latest                   ## locally build image
    # build:                                       ## build image with compose
    #   context: .
    #   dockerfile: docker/Dockerfile.alpine
    environment:
      # Configuration via environment variables.
      # Basic example using Telegram notifications
      # For more options and details visit https://github.com/Der-Henning/tgtg/wiki/Configuration

      - TGTG_USERNAME=walkersky72@gmail.com
      - SLEEP_TIME=60
      - TZ=Australia/Sydney
      - LOCALE=en_AU
      - PORT=3000

      - TELEGRAM=true
      - TELEGRAM_TOKEN=8723457158:AAG5zvrT8KA-vZ9XmhOHhOK1Q9ho-4ZQaR4
      - TELEGRAM_CHAT_IDS=1262901364

    volumes:
      - tokens:/tokens ## volume to save TGTG credentials to reuse on next start up and avoid login mail

    ports:
      - 3000:3000

volumes:
  tokens:
